<!DOCTYPE html> <html <?php language_attributes(); ?>> <head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TMQPRBXQ');</script>
<!-- End Google Tag Manager -->     <meta charset="<?php bloginfo( 'charset' ); ?>">     <meta name="viewport" content="width=device-width, initial-scale=1.0">     <link rel="profile" href="https://gmpg.org/xfn/11">          <style id="mitsune-breadcrumb-polish"> .breadcrumb{margin:0 0 18px;color:#64748b;font-size:13px;line-height:1.4} .breadcrumb ol{display:flex;flex-wrap:wrap;align-items:flex-start;gap:6px;margin:0;padding:0;list-style:none} .breadcrumb li{display:block;min-width:0;max-width:100%;overflow-wrap:anywhere;color:#64748b} .breadcrumb li+li::before{content:'>';margin:0 2px 0 0;color:#94a3b8;font-weight:700} .breadcrumb a{display:inline;max-width:none;overflow:visible;white-space:normal;color:#0369a1;text-decoration:none;font-weight:700} .breadcrumb a:hover{color:#0f172a;text-decoration:underline;text-underline-offset:3px} .breadcrumb li[aria-current="page"]{font-weight:600;color:#475569;overflow:visible;white-space:normal;max-width:100%} @media (max-width:640px){.breadcrumb{font-size:12px;margin-bottom:14px}.breadcrumb li[aria-current="page"]{max-width:100%;white-space:normal}} </style> <style id="mitsune-sidebar-cleanup"> .sidebar .widget:nth-of-type(3), .sidebar .widget:nth-of-type(4){display:none!important} </style> <?php if ( ! function_exists( 'mitsune_translate_sidebar_block_titles' ) ) { function mitsune_translate_sidebar_block_titles( $content ) {     $content = str_replace( '>Recent Posts<', '>&#26368;&#36817;&#12398;&#25237;&#31295;<', $content );     $content = str_replace( '>Categories<', '>&#12459;&#12486;&#12468;&#12522;&#12540;<', $content );     return $content; } add_filter( 'widget_block_content', 'mitsune_translate_sidebar_block_titles', 20 ); } ?> <style id="mitsune-single-hero-no-crop">.single-thumbnail{aspect-ratio:auto!important;background:#f8fafc}.single-thumbnail img{width:100%!important;height:auto!important;object-fit:contain!important}</style> <?php wp_head(); ?> </head> <body <?php body_class(); ?>>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TMQPRBXQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) --> <?php wp_body_open(); ?> <a class="mitsune-skip-link" href="#main">本文へ移動</a>  <div class="site-wrapper">  <header class="site-header">     <div class="header-inner">          <div class="site-branding">             <?php if ( has_custom_logo() ) : ?>                 <?php the_custom_logo(); ?>             <?php else : ?>                 <a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home">                     <span class="site-title"><?php bloginfo( 'name' ); ?></span>                 </a>                 <?php if ( get_bloginfo( 'description' ) ) : ?>                     <span class="site-tagline"><?php bloginfo( 'description' ); ?></span>                 <?php endif; ?>             <?php endif; ?>         </div>          <!-- mitsune-accessible-navigation:start -->
<button class="mitsune-menu-toggle" hidden type="button" aria-controls="site-navigation" aria-expanded="false"><span class="mitsune-menu-toggle__icon" aria-hidden="true"><span></span><span></span><span></span></span><span class="mitsune-menu-toggle__label">メニュー</span></button>
<!-- mitsune-accessible-navigation:end -->
<nav id="site-navigation" class="main-navigation" aria-label="Primary navigation">             <?php             wp_nav_menu( [                 'theme_location' => 'primary',                 'menu_id'        => 'primary-menu',                 'container'      => false,                 'fallback_cb'    => 'mitsune_fallback_nav',             ] );             ?>         </nav>      </div> </header>  <?php function mitsune_fallback_nav() {     echo '<ul>';     echo '<li><a href="' . esc_url( home_url( '/' ) ) . '">&#12507;&#12540;&#12512;</a></li>';     wp_list_pages( [ 'title_li' => '', 'depth' => 1, 'echo' => true ] );     echo '</ul>'; } ?> 