<?php get_header(); ?>  <main class="site-main" id="main">     <div class="container">          <?php mitsune_breadcrumb(); ?>          <div class="content-area">              <div class="primary-content">                 <?php while ( have_posts() ) : the_post(); ?>                      <article id="post-<?php the_ID(); ?>" <?php post_class( 'single-article' ); ?>>                          <header class="single-header">                             <?php if ( has_post_thumbnail() ) : ?>                                 <div class="single-thumbnail">                                     <?php the_post_thumbnail( 'full', [                                         'alt' => esc_attr( get_the_title() ),                                     ] ); ?>                                 </div>                             <?php endif; ?>                              <div class="single-meta">                                 <?php mitsune_the_category_badge(); ?>                                 <!-- mitsune-post-dates:start -->
                                <span class="post-dates">
                                    <time class="post-date" datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>">公開 <?php echo esc_html( get_the_date() ); ?></time>
                                    <?php if ( get_the_modified_time( 'Ymd' ) !== get_the_time( 'Ymd' ) ) : ?>
                                        <time class="post-updated" datetime="<?php echo esc_attr( get_the_modified_date( 'c' ) ); ?>">更新 <?php echo esc_html( get_the_modified_date() ); ?></time>
                                    <?php endif; ?>
                                </span>
                                <!-- mitsune-post-dates:end -->                                 <span class="post-author">                                     <?php esc_html_e( 'by', 'mitsune' ); ?>                                     <?php the_author_posts_link(); ?>                                 </span>                             </div>                              <?php
                            $mitsune_title_parts = preg_split( '/\s*[｜|]\s*/u', get_the_title(), 2 );
                            ?>
                            <h1 class="single-title">
                                <?php echo esc_html( $mitsune_title_parts[0] ); ?>
                                <?php if ( count( $mitsune_title_parts ) === 2 ) : ?><br><?php echo esc_html( $mitsune_title_parts[1] ); ?><?php endif; ?>
                            </h1>                             <hr class="single-divider">                         </header>                          <div class="entry-content">                             <?php the_content(); ?>                         </div>                          <?php                         wp_link_pages( [                             'before' => '<div class="page-links">' . esc_html__( 'ページ:', 'mitsune' ),                             'after'  => '</div>',                         ] );                         ?>                      </article>                      <!-- mitsune-article-end-ad:start -->
<?php if ( function_exists( 'mitsune_render_manual_ad' ) ) mitsune_render_manual_ad( 'article-end' ); ?>
<!-- mitsune-article-end-ad:end --><nav class="post-navigation" aria-label="<?php esc_attr_e( '前後の記事', 'mitsune' ); ?>">                         <div class="nav-previous">                             <?php $prev_post = get_previous_post(); ?>                             <?php if ( $prev_post ) : ?>                                 <span class="nav-label">← <?php esc_html_e( '前の記事', 'mitsune' ); ?></span>                                 <a href="<?php echo esc_url( get_permalink( $prev_post ) ); ?>" class="nav-title">                                     <?php echo esc_html( get_the_title( $prev_post ) ); ?>                                 </a>                             <?php endif; ?>                         </div>                         <div class="nav-next">                             <?php $next_post = get_next_post(); ?>                             <?php if ( $next_post ) : ?>                                 <span class="nav-label"><?php esc_html_e( '次の記事', 'mitsune' ); ?> →</span>                                 <a href="<?php echo esc_url( get_permalink( $next_post ) ); ?>" class="nav-title">                                     <?php echo esc_html( get_the_title( $next_post ) ); ?>                                 </a>                             <?php endif; ?>                         </div>                     </nav>                      <?php mitsune_related_posts( get_the_ID() ); ?>                  <?php endwhile; ?>             </div>              <?php get_sidebar(); ?>          </div>     </div> </main>  <?php get_footer(); ?> 